# Generated by Django 2.2 on 2020-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cotegory',
            field=models.CharField(choices=[('other', 'Розное'), ('food', 'Еда'), ('it', 'IT-сфера'), ('psycho', 'Психология'), ('bikers', 'Велосипеды')], default='other', max_length=20, verbose_name='Тема'),
        ),
    ]
